import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <nav className="relative size-28 w-auto text-black bg-gray border-b-8 border-black flex items-center">
          <ul className="absolute top-1/2 transform -translate-y-1/2 right-10 inline-flex px-10 space-x-12 h-16 items-center">
            <li className="text-2xl font-bold border-b-8 border-l-8 border border-black p-3 ">About</li>
            <li className="text-2xl font-bold border-b-8 border-l-8 border border-black p-3 ">Inspiration</li>
            <li className="text-2xl font-bold border-b-8 border-l-8 border border-black p-3 ">GitHub</li>
            <li className="text-2xl font-bold p-3 pr-7 pl-7 border border-black rounded-full bg-gray-800 text-white">Sign In</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
